name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Create NuGet package
      run: |
        # Extract version from git tag
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "Creating package version: $TAG_VERSION"
        
        # Create the package using dotnet pack
        dotnet pack Template.csproj --configuration Release --output ./packages -p:PackageVersion=$TAG_VERSION
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./packages/*.nupkg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}